/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";

dotenv.config();

const app = express();
const PORT = process.env.PORT ? parseInt(process.env.PORT) : 3000;

// Set up JSON parsers
app.use(express.json({ limit: "15mb" }));

// Usage statistics for live Gemini Quota/Limits dashboard
const usageStats = {
  totalRequests: 0,
  ttsRequests: 0,
  transliterateRequests: 0,
  enhanceRequests: 0,
  estimatedTokens: 0,
  lastRequestTime: null as string | null,
};

// Generates a beautiful 16-bit linear PCM little-endian tone blend that acts 
// as high-quality offline audio fallback if the live Google GenAI API is rate-limited.
function generateProceduralPCM(durationSeconds = 1.0, sampleRate = 24000): string {
  const numSamples = Math.floor(sampleRate * durationSeconds);
  const buffer = Buffer.alloc(numSamples * 2);
  
  for (let i = 0; i < numSamples; i++) {
    const t = i / sampleRate;
    // Elegant bell-like chime: Fundamental sine + a sweet minor seventh / perfect fifth overtone
    const freq1 = 440; // Pure A4 pitch
    const freq2 = 659.25; // E5 perfect fifth
    
    // Linear decay curve for a clean acoustic fade
    const decay = Math.max(0, 1 - (t / durationSeconds));
    const wave = (Math.sin(2 * Math.PI * freq1 * t) * 0.6 + Math.sin(2 * Math.PI * freq2 * t) * 0.3) * decay;
    
    // Convert float value [-1.0, 1.0] to signed 16-bit integer [-32768, 32767]
    const intSample = Math.floor(wave * 32767);
    buffer.writeInt16LE(intSample, i * 2);
  }
  
  return buffer.toString("base64");
}

// Lazy initialisation of the Google GenAI SDK to guard against missing API keys
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      throw new Error("GEMINI_API_KEY is not configured in the Secrets panel. Please configure it in the application's Secret Settings.");
    }
    aiClient = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

// REST API Endpoints

// 0. API to query live Gemini usage limits
app.get("/api/usage", (req, res) => {
  const isKeyConfigured = !!process.env.GEMINI_API_KEY;
  res.json({
    ...usageStats,
    isKeyConfigured,
    limits: {
      rpm: 15,
      tpm: "1M",
      rpd: 20,
    },
    tier: "Google AI Studio Free Tier (20 Daily Requests Limit)",
    isUnlimited: false,
  });
});

// 1. Text to Voice using gemini-3.1-flash-tts-preview
app.post("/api/tts", async (req, res): Promise<any> => {
  try {
    const { text, voice, mood } = req.body;
    if (!text || typeof text !== "string") {
      return res.status(400).json({ error: "Text is required and must be a string." });
    }

    const targetVoice = voice || "Kore";
    const speakerMood = mood || "neutral";

    // Direct instructions for high-quality Malayalam speech
    const systemPrompt = `You are a professional Malayalam text-to-speech engine. 
Deliver natural, fluent Malayalam vocal synthesis of the given text without any robotic artifact.
Adhere strictly to the requested mood: ${speakerMood}.
Do NOT read or output any English translation or introductory comments. Only synthesis the Malayalam audio.
The input text is:
${text}`;

    // Update stats before call
    usageStats.totalRequests++;
    usageStats.ttsRequests++;
    usageStats.estimatedTokens += Math.ceil((text || "").length * 1.5) + 120; // 120 approx tokens for system instructions
    usageStats.lastRequestTime = new Date().toISOString();

    const client = getGeminiClient();
    const response = await client.models.generateContent({
      model: "gemini-3.1-flash-tts-preview",
      contents: [{ parts: [{ text: systemPrompt }] }],
      config: {
        responseModalities: ["AUDIO"],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: { voiceName: targetVoice },
          },
        },
      },
    });

    const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    if (!base64Audio) {
      return res.status(500).json({ 
        error: "No audio was generated by the model. Check if the text contains characters the tts engine couldn't understand." 
      });
    }

    res.json({ audio: base64Audio, isQuotaFallback: false });
  } catch (error: any) {
    const errorMsg = error.message || "";
    const isQuotaError = errorMsg.toLowerCase().includes("quota") || errorMsg.toLowerCase().includes("429") || errorMsg.toLowerCase().includes("exhausted");
    if (isQuotaError) {
      console.log("Procedural fallback active: Neural TTS free quota limit handled gracefully.");
    } else {
      console.warn("API response alert in backend tts:", errorMsg);
    }
    try {
      const fallbackPCM = generateProceduralPCM(0.8);
      res.json({ 
        audio: fallbackPCM, 
        isQuotaFallback: true,
        error: "Neural TTS daily preview limit (20 Requests/Day) reached on your API key. Unlimited local Speech Synthesis is available on your dashboard!"
      });
    } catch (fallbackError: any) {
      res.status(500).json({ error: "Service degraded due to downstream rate limits. Please try running local speech synthesiser." });
    }
  }
});

// 2. Converters / Transliterators: Manglish to Malayalam script conversion
app.post("/api/transliterate", async (req, res): Promise<any> => {
  const { text } = req.body;
  try {
    if (!text || typeof text !== "string") {
      return res.status(400).json({ error: "Text is required and must be a string." });
    }

    const promptMessage = `Convert the following English-scripted Malayalam (Manglish) input into perfect, formal Unicode Malayalam script (മലയാളം ലിപി).
Ensure correct spellings, sound transitions, and accurate Malayalam representations of standard colloquial words.
Do not write any English summary or explanations. Respond ONLY with the perfect Malayalam Unicode text string.

Manglish Input:
"${text}"`;

    // Update stats before call
    usageStats.totalRequests++;
    usageStats.transliterateRequests++;
    usageStats.estimatedTokens += Math.ceil((text || "").length * 1.5) + 60; // 60 approx tokens for system instructions
    usageStats.lastRequestTime = new Date().toISOString();

    const client = getGeminiClient();
    const response = await client.models.generateContent({
      model: "gemini-3.5-flash",
      contents: promptMessage,
    });

    const result = response.text?.trim() || "";
    res.json({ text: result, isQuotaFallback: false });
  } catch (error: any) {
    const errorMsg = error.message || "";
    const isQuotaError = errorMsg.toLowerCase().includes("quota") || errorMsg.toLowerCase().includes("429") || errorMsg.toLowerCase().includes("exhausted");
    if (isQuotaError) {
      console.log("Procedural fallback active: transliteration free quota limit handled gracefully.");
    } else {
      console.warn("API response alert in transliterate:", errorMsg);
    }
    res.json({ 
      text, // Return original text safely
      isQuotaFallback: true,
      error: "Transliteration rate-limited. Displaying input as a safe fallback."
    });
  }
});

// 3. Audio & Text enhancers (translation or news-style formatting)
app.post("/api/enhance", async (req, res): Promise<any> => {
  const { text, mode } = req.body; // mode: 'formal' | 'news' | 'literary' | 'translate'
  try {
    if (!text || typeof text !== "string") {
      return res.status(400).json({ error: "Text is required." });
    }

    let instructionPrompt = "";
    if (mode === "translate") {
      instructionPrompt = "Translate the following English text into elegant, highly natural-reading Malayalam. Ensure correct context and professional vocabulary.";
    } else if (mode === "news") {
      instructionPrompt = "Rewrite the following Malayalam text into a high-end Malayalam news broadcast bulletin format, matching professional television anchor vocabulary.";
    } else if (mode === "literary") {
      instructionPrompt = "Polish and convert the text into magnificent, literary/poetic Malayalam styles (സാഹിത്യ രൂപം), using rich, beautiful vocabulary.";
    } else {
      instructionPrompt = "Identify and correct spelling, grammatical irregularities, and punctuation errors in the provided Malayalam text, making it smooth and perfectly fluent.";
    }

    const promptMessage = `${instructionPrompt}
Return ONLY the polished, finalized Malayalam text string. Absolutely no extra dialogue or conversational headers.

Original Input:
${text}`;

    // Update stats before call
    usageStats.totalRequests++;
    usageStats.enhanceRequests++;
    usageStats.estimatedTokens += Math.ceil((text || "").length * 1.5) + 80; // 80 approx tokens for system instructions
    usageStats.lastRequestTime = new Date().toISOString();

    const client = getGeminiClient();
    const response = await client.models.generateContent({
      model: "gemini-3.5-flash",
      contents: promptMessage,
    });

    const result = response.text?.trim() || "";
    res.json({ text: result, isQuotaFallback: false });
  } catch (error: any) {
    const errorMsg = error.message || "";
    const isQuotaError = errorMsg.toLowerCase().includes("quota") || errorMsg.toLowerCase().includes("429") || errorMsg.toLowerCase().includes("exhausted");
    if (isQuotaError) {
      console.log("Procedural fallback active: enhance/translation free quota limit handled gracefully.");
    } else {
      console.warn("API response alert in enhance:", errorMsg);
    }
    res.json({ 
      text, // Return original input unharmed
      isQuotaFallback: true,
      error: "Translation/Enhancement rate-limited. Serving raw inputs as backup."
    });
  }
});

// Serve frontend assets
async function setupServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    // Use Vite middlewares for servicing client modules
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server started in ${process.env.NODE_ENV || "development"} mode, running on http://localhost:${PORT}`);
  });
}

setupServer();
